spring:
# application
  application:
    name: hex-verify-cpf
    title: Service of Verify Client CPF - LAB
    version: v1.0
    formatted-version: ☕︎ Version 1.0 - to building 
    author: Alejandro Fuentes - io.gitlab.alefuentes

  # db
  data:
    mongodb:
      uri: mongodb://localhost:27017/hexa-ale

arantes:
  client:
    address:
      url: http://localhost:8082/address


