# server
server:
  port: 8081

spring:
# application
  application:
    name: hex-verify-cpf
    title: Service of Verify Client CPF - LAB
    version: v1.0
    formatted-version: ☕︎ Version 1.0 - to building 
    author: Alejandro Fuentes - io.gitlab.alefuentes

  # db
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      database: hexa-ale
      username: root
      password: example

arantes:
  client:
    address:
      url: http://localhost:8082/addresses


